# Generated by Django 5.2.8 on 2026-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='temp_slug', unique=True),
            preserve_default=False,
        ),
    ]
