# Generated by Django 6.0.2 on 2026-02-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='Post Title'),
            preserve_default=False,
        ),
    ]
