# Generated by Django 6.0.2 on 2026-02-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
