from django.db import models
from django.core.validators import MinValueValidator
# from django.db.models import F, Sum
# from cart.models import CartItem, Cart

# Create your models here.
# all id fields are auto generated by django, so they are unneccessary 
class Category(models.Model):
    # id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    # content_count = models.IntegerField(default=0)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = "Category"
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.name

class Product(models.Model):
    # id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    # stock = models.IntegerField(min_value=0, default=0)
    # there is nothing like min_value in django models, i have to import the validators from django core to validate this
    stock = models.IntegerField(default=0, validators=[MinValueValidator(0)] )
    is_available = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    provider = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    image_url = models.URLField(blank=True)
    category = models.ForeignKey(
        Category, 
        on_delete=models.CASCADE, 
        related_name='products'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Products"
        ordering = ['name']

    def __str__(self):
        return self.name


# class CartItem(models.Model):
#     # id = models.AutoField(primary_key=True)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     # we can use the related name 'items' to access the cart items from the cart model, so we don't need to add a related name here
#     cart = models.ForeignKey('Cart', on_delete=models.CASCADE, related_name='items')
#     # unique_together = ('product', 'cart')
#     # unique here won't work, i have to put it in class meta
#     # quantity = models.IntegerField(min_value=1, default=1)
#     quantity = models.IntegerField(default=1, validators = [MinValueValidator(1)])
#     added_at = models.DateTimeField(auto_now_add=True)
    
#     class Meta:
#         # unique_together = ('product', 'cart')
#         # the method below is the more advanced method 
#         constraints = [
#             models.UniqueConstraint(fields= ['product', 'cart'], name='unique_product_cart')
#         ]
#         verbose_name_plural = "Cart Items"
#         ordering = ['-added_at']
        

#     def __str__(self):
#         return f"{self.quantity} x {self.product.name}"

# class Cart (models.Model):
#     # id = models.AutoField(primary_key=True)
#     # a dummy field until we implement user authentication
#     user = models.CharField(max_length=100)
#     created_at = models.DateTimeField(auto_now_add=True)
    
#     def __str__(self):
#         return f"Cart of {self.user}"
    
#     def total_price(self):
#         total = 0
#         # for item in self.items.all():
#         #     total += item.product.price * item.quantity
        
#         # this is supposed to calculate the sum in sql itself instead of sending all the rows to python then calculate it
#         # F means field reference inside the sql database
#         # it also is great in race conditions
        
#         # aggregate returns one value, annotate edits in all rows
#         return self.items.aggregate(
#             total = Sum(F('product__price') * F('quantity'))
#         )['total'][0]
