# Generated by Django 6.0.5 on 2026-05-06 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('muscle_mass_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('water_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('visceral_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bone_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('basal_metabolism_kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('body_age', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('protein_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('subcutaneous_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='analysis.analysisresult')),
            ],
            options={
                'db_table': 'body_measurements',
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
