# Generated by Django 6.0.5 on 2026-05-06 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bodymeasurement',
            index=models.Index(fields=['user', 'date'], name='body_measur_user_id_33d4bc_idx'),
        ),
    ]
