# Generated by Django 5.2.8 on 2026-04-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Invitations', '0001_initial'),
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.room'),
        ),
    ]
