# Generated by Django 5.2.8 on 2026-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('reading_date_time', models.DateTimeField()),
                ('reading_amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
