# Generated by Django 5.2.8 on 2026-05-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Readings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='reading_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
