# Generated by Django 6.0.2 on 2026-02-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_category_options_product_images_filenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images_filenames',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
