# Generated by Django 6.0.3 on 2026-03-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('INTEREST_ADDITION', 'Interest Addition')]),
        ),
    ]
