# Generated by Django 6.0.3 on 2026-03-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bankadmin',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='bankadmin',
            old_name='user_id',
            new_name='user',
        ),
    ]
