# Generated by Django 6.0.2 on 2026-02-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
