# Generated by Django 5.2.11 on 2026-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('smart phone', 'smart phone'), ('electronic device', 'electronic device'), ('furniture', 'furniture')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='no description.', null=True),
        ),
    ]
