# Generated by Django 6.0.2 on 2026-02-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('smart phones', 'smart phones'), ('electronic devices', 'electronic devices'), ('furniture', 'furniture'), ('books', 'books'), ('laptops', 'laptops')], max_length=50, null=True),
        ),
    ]
