# Generated by Django 6.0.3 on 2026-03-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='amount',
            new_name='balance',
        ),
    ]
