# Generated by Django 6.0.5 on 2026-05-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('parsed_metrics', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ('-analyzed_at',),
            },
        ),
    ]
