# Generated by Django 4.2.28 on 2026-04-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Adhkar", "0002_category_reward_rename_contثnt_adhkar_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adhkar",
            old_name="Category",
            new_name="category",
        ),
    ]
