# Generated by Django 4.2.28 on 2026-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Adhkar", "0003_rename_category_adhkar_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="rewards/"),
        ),
    ]
