# Generated by Django 5.2.8 on 2026-03-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='target_account',
            new_name='target_account_id',
        ),
    ]
