# Generated by Django 5.2.8 on 2026-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books'), ('clothes', 'Clothes'), ('toys', 'Toys')], default='electronics', max_length=50)),
                ('image', models.ImageField(upload_to='products/images/%y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
