# Generated by Django 6.0.2 on 2026-05-03 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_reportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('accept', 'Accept'), ('invite', 'Invite'), ('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('change_role', 'Change Role'), ('run_schedule', 'Run Schedule')], max_length=30)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='expenses.panel')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['panel', 'created_at'], name='audit_logs_panel_i_034378_idx'), models.Index(fields=['actor', 'created_at'], name='audit_logs_actor_i_5bd818_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx')],
            },
        ),
    ]
