# Generated by Django 6.0.2 on 2026-05-03 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('events', models.JSONField(default=list)),
                ('secret', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='expenses.panel')),
            ],
            options={
                'db_table': 'webhooks',
                'indexes': [models.Index(fields=['panel', 'is_active'], name='webhooks_panel_i_d30e38_idx')],
            },
        ),
    ]
