# Generated by Django 5.2.8 on 2026-04-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='reading_deadline',
            field=models.TimeField(),
        ),
    ]
