# Generated by Django 6.0.2 on 2026-03-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='Account Number')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Balance')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='Is Frozen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
