# Generated by Django 6.0.2 on 2026-02-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Garden'), ('books', 'Books'), ('toys', 'Toys & Games'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('automotive', 'Automotive'), ('health', 'Health & Wellness'), ('grocery', 'Grocery & Gourmet Food')], max_length=50)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
